"""initial baseline

Revision ID: 096f952de48e
Revises: 
Create Date: 2026-10-03 18:12:54.517317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '096f952de48e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_permission',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='权限ID'),
    sa.Column('permission_code', sa.String(length=128), nullable=False, comment='权限编码'),
    sa.Column('permission_name', sa.String(length=128), nullable=False, comment='权限名称'),
    sa.Column('permission_type', sa.String(length=16), nullable=False, comment='权限类型：MENU/API/BUTTON'),
    sa.Column('path', sa.String(length=255), nullable=True, comment='前端路由或接口路径'),
    sa.Column('method', sa.String(length=16), nullable=True, comment='HTTP方法'),
    sa.Column('parent_id', mysql.BIGINT(unsigned=True), nullable=True, comment='父权限ID'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='状态：0禁用，1启用'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_permission.id'], name='fk_sys_permission_parent'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission_code', name='uk_sys_permission_code'),
    comment='系统权限表'
    )
    op.create_index('idx_sys_permission_parent_id', 'sys_permission', ['parent_id'], unique=False)
    op.create_index('idx_sys_permission_type_status', 'sys_permission', ['permission_type', 'status'], unique=False)
    op.create_table('sys_role',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='角色ID'),
    sa.Column('role_code', sa.String(length=64), nullable=False, comment='角色编码'),
    sa.Column('role_name', sa.String(length=64), nullable=False, comment='角色名称'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='角色描述'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='状态：0禁用，1启用'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_code', name='uk_sys_role_code'),
    comment='系统角色表'
    )
    op.create_index('idx_sys_role_status', 'sys_role', ['status'], unique=False)
    op.create_table('sys_user',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=64), nullable=False, comment='登录用户名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('nickname', sa.String(length=64), nullable=True, comment='用户昵称'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=32), nullable=True, comment='手机号'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='状态：0禁用，1启用'),
    sa.Column('last_login_at', mysql.DATETIME(fsp=3), nullable=True, comment='最后登录时间'),
    sa.Column('last_login_ip', sa.String(length=64), nullable=True, comment='最后登录IP'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(fsp=3), nullable=True, comment='软删除时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uk_sys_user_email'),
    sa.UniqueConstraint('username', name='uk_sys_user_username'),
    comment='系统用户表'
    )
    op.create_index('idx_sys_user_deleted_at', 'sys_user', ['deleted_at'], unique=False)
    op.create_index('idx_sys_user_status', 'sys_user', ['status'], unique=False)
    op.create_table('alert_rule',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='告警规则ID'),
    sa.Column('rule_name', sa.String(length=128), nullable=False, comment='规则名称'),
    sa.Column('metric_type', sa.String(length=64), nullable=False, comment='CPU/MEMORY/DISK/LOAD/AGENT/SERVICE/CONTAINER'),
    sa.Column('target_type', sa.String(length=32), server_default=sa.text("'SERVER'"), nullable=False, comment='SERVER/DISK/CONTAINER/SERVICE'),
    sa.Column('severity', sa.String(length=16), nullable=False, comment='WARNING/CRITICAL'),
    sa.Column('operator', sa.String(length=8), nullable=False, comment='GT/GTE/LT/LTE/EQ'),
    sa.Column('threshold', sa.Numeric(precision=12, scale=4), nullable=True, comment='数值阈值'),
    sa.Column('duration_seconds', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=False, comment='持续异常时间，单位：秒'),
    sa.Column('recovery_threshold', sa.Numeric(precision=12, scale=4), nullable=True, comment='恢复阈值，可为空'),
    sa.Column('enabled', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='是否启用'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='规则描述'),
    sa.Column('created_by', mysql.BIGINT(unsigned=True), nullable=True, comment='创建人'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['sys_user.id'], name='fk_alert_rule_created_by'),
    sa.PrimaryKeyConstraint('id'),
    comment='告警规则表'
    )
    op.create_index('fk_alert_rule_created_by', 'alert_rule', ['created_by'], unique=False)
    op.create_index('idx_alert_rule_metric_enabled', 'alert_rule', ['metric_type', 'enabled'], unique=False)
    op.create_index('idx_alert_rule_target_enabled', 'alert_rule', ['target_type', 'enabled'], unique=False)
    op.create_table('ops_server',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='服务器ID'),
    sa.Column('server_code', sa.String(length=64), nullable=False, comment='服务器唯一编码'),
    sa.Column('hostname', sa.String(length=128), nullable=False, comment='主机名'),
    sa.Column('ip_address', sa.String(length=64), nullable=False, comment='服务器IP地址'),
    sa.Column('ssh_port', mysql.SMALLINT(unsigned=True), server_default=sa.text('22'), nullable=False, comment='SSH端口'),
    sa.Column('os_name', sa.String(length=128), nullable=True, comment='操作系统名称'),
    sa.Column('os_version', sa.String(length=128), nullable=True, comment='操作系统版本'),
    sa.Column('kernel_version', sa.String(length=128), nullable=True, comment='内核版本'),
    sa.Column('architecture', sa.String(length=32), nullable=True, comment='系统架构'),
    sa.Column('cpu_model', sa.String(length=255), nullable=True, comment='CPU型号'),
    sa.Column('cpu_cores', mysql.INTEGER(unsigned=True), nullable=True, comment='CPU逻辑核心数'),
    sa.Column('memory_total_bytes', mysql.BIGINT(unsigned=True), nullable=True, comment='内存总量，单位：字节'),
    sa.Column('disk_total_bytes', mysql.BIGINT(unsigned=True), nullable=True, comment='磁盘总量，单位：字节'),
    sa.Column('agent_version', sa.String(length=32), nullable=True, comment='Agent版本'),
    sa.Column('agent_status', sa.String(length=16), server_default=sa.text("'OFFLINE'"), nullable=False, comment='Agent状态：ONLINE/WARNING/OFFLINE/UNKNOWN'),
    sa.Column('last_heartbeat_at', mysql.DATETIME(fsp=3), nullable=True, comment='最后心跳时间'),
    sa.Column('registered_at', mysql.DATETIME(fsp=3), nullable=True, comment='Agent注册时间'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='资产状态：0停用，1启用'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('created_by', mysql.BIGINT(unsigned=True), nullable=True, comment='创建人'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(fsp=3), nullable=True, comment='软删除时间'),
    sa.ForeignKeyConstraint(['created_by'], ['sys_user.id'], name='fk_ops_server_created_by'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address', 'ssh_port', name='uk_ops_server_ip_port'),
    sa.UniqueConstraint('server_code', name='uk_ops_server_code'),
    comment='服务器资产表'
    )
    op.create_index('fk_ops_server_created_by', 'ops_server', ['created_by'], unique=False)
    op.create_index('idx_ops_server_agent_status', 'ops_server', ['agent_status'], unique=False)
    op.create_index('idx_ops_server_hostname', 'ops_server', ['hostname'], unique=False)
    op.create_index('idx_ops_server_last_heartbeat', 'ops_server', ['last_heartbeat_at'], unique=False)
    op.create_index('idx_ops_server_status', 'ops_server', ['status'], unique=False)
    op.create_table('ops_task',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='任务ID'),
    sa.Column('task_name', sa.String(length=128), nullable=False, comment='任务名称'),
    sa.Column('task_type', sa.String(length=32), nullable=False, comment='SERVICE_CHECK/SERVICE_ACTION/SHELL_LIMITED'),
    sa.Column('action', sa.String(length=32), nullable=True, comment='STATUS/START/STOP/RESTART'),
    sa.Column('service_name', sa.String(length=64), nullable=True, comment='经过白名单校验的服务名称'),
    sa.Column('schedule_type', sa.String(length=16), server_default=sa.text("'ONCE'"), nullable=False, comment='ONCE/CRON'),
    sa.Column('cron_expression', sa.String(length=128), nullable=True, comment='Cron表达式'),
    sa.Column('status', sa.String(length=24), server_default=sa.text("'CREATED'"), nullable=False, comment='CREATED/PENDING/RUNNING/SUCCESS/FAILED/TIMEOUT/CANCELLED'),
    sa.Column('created_by', mysql.BIGINT(unsigned=True), nullable=False, comment='创建人'),
    sa.Column('started_at', mysql.DATETIME(fsp=3), nullable=True, comment='开始时间'),
    sa.Column('finished_at', mysql.DATETIME(fsp=3), nullable=True, comment='结束时间'),
    sa.Column('timeout_seconds', mysql.INTEGER(unsigned=True), server_default=sa.text('300'), nullable=False, comment='超时时间，单位：秒'),
    sa.Column('confirmation_required', mysql.TINYINT(), server_default=sa.text('0'), nullable=False, comment='是否需要二次确认'),
    sa.Column('confirmed_by', mysql.BIGINT(unsigned=True), nullable=True, comment='确认人'),
    sa.Column('confirmed_at', mysql.DATETIME(fsp=3), nullable=True, comment='确认时间'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['sys_user.id'], name='fk_ops_task_confirmed_by'),
    sa.ForeignKeyConstraint(['created_by'], ['sys_user.id'], name='fk_ops_task_created_by'),
    sa.PrimaryKeyConstraint('id'),
    comment='运维任务表'
    )
    op.create_index('fk_ops_task_confirmed_by', 'ops_task', ['confirmed_by'], unique=False)
    op.create_index('idx_ops_task_creator_time', 'ops_task', ['created_by', 'created_at'], unique=False)
    op.create_index('idx_ops_task_schedule', 'ops_task', ['schedule_type', 'status'], unique=False)
    op.create_index('idx_ops_task_status', 'ops_task', ['status'], unique=False)
    op.create_table('sys_login_log',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='登录日志ID'),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=True, comment='用户ID，登录失败时可为空'),
    sa.Column('username', sa.String(length=64), nullable=False, comment='登录用户名'),
    sa.Column('login_ip', sa.String(length=64), nullable=True, comment='登录IP'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='浏览器User-Agent'),
    sa.Column('login_status', sa.String(length=16), nullable=False, comment='SUCCESS/FAILED/LOCKED'),
    sa.Column('failure_reason', sa.String(length=255), nullable=True, comment='失败原因'),
    sa.Column('request_id', sa.String(length=64), nullable=True, comment='请求ID'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], name='fk_sys_login_log_user'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户登录日志表'
    )
    op.create_index('idx_sys_login_log_status_time', 'sys_login_log', ['login_status', 'created_at'], unique=False)
    op.create_index('idx_sys_login_log_user_time', 'sys_login_log', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_sys_login_log_username_time', 'sys_login_log', ['username', 'created_at'], unique=False)
    op.create_table('sys_role_permission',
    sa.Column('role_id', mysql.BIGINT(unsigned=True), nullable=False, comment='角色ID'),
    sa.Column('permission_id', mysql.BIGINT(unsigned=True), nullable=False, comment='权限ID'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['sys_permission.id'], name='fk_sys_role_permission_permission'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], name='fk_sys_role_permission_role'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    comment='角色权限关联表'
    )
    op.create_index('idx_sys_role_permission_permission_id', 'sys_role_permission', ['permission_id'], unique=False)
    op.create_table('sys_user_role',
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False, comment='用户ID'),
    sa.Column('role_id', mysql.BIGINT(unsigned=True), nullable=False, comment='角色ID'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], name='fk_sys_user_role_role'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], name='fk_sys_user_role_user'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    comment='用户角色关联表'
    )
    op.create_index('idx_sys_user_role_role_id', 'sys_user_role', ['role_id'], unique=False)
    op.create_table('alert_event',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='告警事件ID'),
    sa.Column('rule_id', mysql.BIGINT(unsigned=True), nullable=False, comment='告警规则ID'),
    sa.Column('server_id', mysql.BIGINT(unsigned=True), nullable=True, comment='服务器ID'),
    sa.Column('resource_type', sa.String(length=32), server_default=sa.text("'SERVER'"), nullable=False, comment='资源类型'),
    sa.Column('resource_id', mysql.BIGINT(unsigned=True), nullable=True, comment='资源ID'),
    sa.Column('alert_key', sa.String(length=255), nullable=False, comment='告警指纹，用于活动告警去重'),
    sa.Column('metric_type', sa.String(length=64), nullable=False, comment='指标类型'),
    sa.Column('severity', sa.String(length=16), nullable=False, comment='WARNING/CRITICAL'),
    sa.Column('status', sa.String(length=24), server_default=sa.text("'PENDING'"), nullable=False, comment='PENDING/FIRING/ACKNOWLEDGED/RESOLVED'),
    sa.Column('is_active', mysql.TINYINT(), sa.Computed("CASE WHEN status IN ('PENDING', 'FIRING', 'ACKNOWLEDGED') THEN 1 ELSE NULL END", persisted=True), nullable=True, comment='活动告警标记，用于唯一约束'),
    sa.Column('first_fired_at', mysql.DATETIME(fsp=3), nullable=True, comment='首次触发时间'),
    sa.Column('last_fired_at', mysql.DATETIME(fsp=3), nullable=True, comment='最近触发时间'),
    sa.Column('acknowledged_by', mysql.BIGINT(unsigned=True), nullable=True, comment='确认人'),
    sa.Column('acknowledged_at', mysql.DATETIME(fsp=3), nullable=True, comment='确认时间'),
    sa.Column('resolved_at', mysql.DATETIME(fsp=3), nullable=True, comment='恢复时间'),
    sa.Column('current_value', sa.Numeric(precision=12, scale=4), nullable=True, comment='当前指标值'),
    sa.Column('threshold_value', sa.Numeric(precision=12, scale=4), nullable=True, comment='触发阈值'),
    sa.Column('message', sa.String(length=500), nullable=False, comment='告警消息'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['sys_user.id'], name='fk_alert_event_acknowledged_by'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rule.id'], name='fk_alert_event_rule'),
    sa.ForeignKeyConstraint(['server_id'], ['ops_server.id'], name='fk_alert_event_server'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_key', 'is_active', name='uk_alert_event_active_key'),
    comment='告警事件表'
    )
    op.create_index('fk_alert_event_acknowledged_by', 'alert_event', ['acknowledged_by'], unique=False)
    op.create_index('idx_alert_event_rule_id', 'alert_event', ['rule_id'], unique=False)
    op.create_index('idx_alert_event_server_status', 'alert_event', ['server_id', 'status'], unique=False)
    op.create_index('idx_alert_event_status_time', 'alert_event', ['status', 'created_at'], unique=False)
    op.create_table('monitor_process_snapshot',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='进程快照记录ID'),
    sa.Column('server_id', mysql.BIGINT(unsigned=True), nullable=False, comment='服务器ID'),
    sa.Column('process_pid', mysql.INTEGER(unsigned=True), nullable=False, comment='进程PID'),
    sa.Column('process_name', sa.String(length=255), nullable=True, comment='进程名称'),
    sa.Column('username', sa.String(length=128), nullable=True, comment='进程所属用户'),
    sa.Column('cpu_percent', sa.Numeric(precision=7, scale=3), nullable=True, comment='进程CPU使用率'),
    sa.Column('memory_percent', sa.Numeric(precision=7, scale=3), nullable=True, comment='进程内存使用率'),
    sa.Column('memory_bytes', mysql.BIGINT(unsigned=True), nullable=True, comment='进程内存占用'),
    sa.Column('process_status', sa.String(length=32), nullable=True, comment='进程状态'),
    sa.Column('command_line', sa.Text(), nullable=True, comment='命令行，注意脱敏'),
    sa.Column('collected_at', mysql.DATETIME(fsp=3), nullable=False, comment='采集时间'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['ops_server.id'], name='fk_monitor_process_snapshot_server'),
    sa.PrimaryKeyConstraint('id'),
    comment='服务器进程快照表'
    )
    op.create_index('idx_monitor_process_snapshot_server_pid_time', 'monitor_process_snapshot', ['server_id', 'process_pid', 'collected_at'], unique=False)
    op.create_index('idx_monitor_process_snapshot_server_time', 'monitor_process_snapshot', ['server_id', 'collected_at'], unique=False)
    op.create_table('monitor_server_metric',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='指标记录ID'),
    sa.Column('server_id', mysql.BIGINT(unsigned=True), nullable=False, comment='服务器ID'),
    sa.Column('collected_at', mysql.DATETIME(fsp=3), nullable=False, comment='采集时间'),
    sa.Column('cpu_usage', sa.Numeric(precision=5, scale=2), nullable=True, comment='CPU使用率，百分比'),
    sa.Column('memory_usage', sa.Numeric(precision=5, scale=2), nullable=True, comment='内存使用率，百分比'),
    sa.Column('memory_used_bytes', mysql.BIGINT(unsigned=True), nullable=True, comment='已使用内存，单位：字节'),
    sa.Column('disk_usage', sa.Numeric(precision=5, scale=2), nullable=True, comment='整体磁盘使用率，百分比'),
    sa.Column('network_in_bytes', mysql.BIGINT(unsigned=True), nullable=True, comment='累计入站字节数'),
    sa.Column('network_out_bytes', mysql.BIGINT(unsigned=True), nullable=True, comment='累计出站字节数'),
    sa.Column('load_1m', sa.Numeric(precision=10, scale=2), nullable=True, comment='1分钟Load'),
    sa.Column('load_5m', sa.Numeric(precision=10, scale=2), nullable=True, comment='5分钟Load'),
    sa.Column('load_15m', sa.Numeric(precision=10, scale=2), nullable=True, comment='15分钟Load'),
    sa.Column('tcp_connections', mysql.INTEGER(unsigned=True), nullable=True, comment='TCP连接数'),
    sa.Column('uptime_seconds', mysql.BIGINT(unsigned=True), nullable=True, comment='系统运行时长，单位：秒'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['ops_server.id'], name='fk_monitor_server_metric_server'),
    sa.PrimaryKeyConstraint('id'),
    comment='服务器监控指标表'
    )
    op.create_index('idx_monitor_server_metric_collected_at', 'monitor_server_metric', ['collected_at'], unique=False)
    op.create_index('idx_monitor_server_metric_server_time', 'monitor_server_metric', ['server_id', 'collected_at'], unique=False)
    op.create_table('ops_agent_heartbeat',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='心跳记录ID'),
    sa.Column('server_id', mysql.BIGINT(unsigned=True), nullable=False, comment='服务器ID'),
    sa.Column('agent_version', sa.String(length=32), nullable=True, comment='Agent版本'),
    sa.Column('ip_address', sa.String(length=64), nullable=True, comment='Agent上报IP'),
    sa.Column('collected_at', mysql.DATETIME(fsp=3), nullable=False, comment='心跳时间'),
    sa.Column('received_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='服务端接收时间'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['ops_server.id'], name='fk_ops_agent_heartbeat_server'),
    sa.PrimaryKeyConstraint('id'),
    comment='Agent心跳历史表'
    )
    op.create_index('idx_ops_agent_heartbeat_received_at', 'ops_agent_heartbeat', ['received_at'], unique=False)
    op.create_index('idx_ops_agent_heartbeat_server_time', 'ops_agent_heartbeat', ['server_id', 'collected_at'], unique=False)
    op.create_table('ops_agent_token',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='Token记录ID'),
    sa.Column('server_id', mysql.BIGINT(unsigned=True), nullable=False, comment='服务器ID'),
    sa.Column('token_name', sa.String(length=64), nullable=False, comment='Token名称'),
    sa.Column('token_prefix', sa.String(length=16), nullable=False, comment='Token前缀，用于识别'),
    sa.Column('token_hash', mysql.CHAR(length=64), nullable=False, comment='Token哈希，不保存明文'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='状态：0撤销，1有效'),
    sa.Column('expires_at', mysql.DATETIME(fsp=3), nullable=True, comment='过期时间'),
    sa.Column('last_used_at', mysql.DATETIME(fsp=3), nullable=True, comment='最后使用时间'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('revoked_at', mysql.DATETIME(fsp=3), nullable=True, comment='撤销时间'),
    sa.ForeignKeyConstraint(['server_id'], ['ops_server.id'], name='fk_ops_agent_token_server'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uk_ops_agent_token_hash'),
    comment='Agent鉴权Token表'
    )
    op.create_index('idx_ops_agent_token_server_status', 'ops_agent_token', ['server_id', 'status'], unique=False)
    op.create_table('ops_server_container',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='容器资产ID'),
    sa.Column('server_id', mysql.BIGINT(unsigned=True), nullable=False, comment='服务器ID'),
    sa.Column('container_id', sa.String(length=128), nullable=False, comment='容器ID'),
    sa.Column('container_name', sa.String(length=255), nullable=False, comment='容器名称'),
    sa.Column('image_name', sa.String(length=255), nullable=True, comment='镜像名称'),
    sa.Column('container_status', sa.String(length=32), nullable=True, comment='RUNNING/STOPPED/PAUSED/EXITED'),
    sa.Column('restart_count', mysql.INTEGER(unsigned=True), nullable=True, comment='重启次数'),
    sa.Column('container_created_at', mysql.DATETIME(fsp=3), nullable=True, comment='容器创建时间'),
    sa.Column('is_critical', mysql.TINYINT(), server_default=sa.text('0'), nullable=False, comment='是否为关键容器'),
    sa.Column('last_seen_at', mysql.DATETIME(fsp=3), nullable=True, comment='最后发现时间'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='状态：0停用，1启用'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['ops_server.id'], name='fk_ops_server_container_server'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'container_id', name='uk_ops_server_container'),
    comment='Docker容器资产表'
    )
    op.create_index('idx_ops_server_container_critical', 'ops_server_container', ['is_critical', 'container_status'], unique=False)
    op.create_index('idx_ops_server_container_status', 'ops_server_container', ['server_id', 'container_status'], unique=False)
    op.create_table('ops_server_disk',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='磁盘资产ID'),
    sa.Column('server_id', mysql.BIGINT(unsigned=True), nullable=False, comment='服务器ID'),
    sa.Column('device_name', sa.String(length=128), nullable=False, comment='设备名称'),
    sa.Column('mount_point', sa.String(length=255), nullable=True, comment='挂载点'),
    sa.Column('filesystem', sa.String(length=64), nullable=True, comment='文件系统'),
    sa.Column('total_bytes', mysql.BIGINT(unsigned=True), nullable=True, comment='磁盘总量，单位：字节'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='状态：0停用，1启用'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['ops_server.id'], name='fk_ops_server_disk_server'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'device_name', 'mount_point', name='uk_ops_server_disk'),
    comment='服务器磁盘资产表'
    )
    op.create_index('idx_ops_server_disk_server_id', 'ops_server_disk', ['server_id'], unique=False)
    op.create_table('ops_server_network',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='网卡资产ID'),
    sa.Column('server_id', mysql.BIGINT(unsigned=True), nullable=False, comment='服务器ID'),
    sa.Column('interface_name', sa.String(length=128), nullable=False, comment='网卡名称'),
    sa.Column('mac_address', sa.String(length=64), nullable=True, comment='MAC地址'),
    sa.Column('ip_address', sa.String(length=64), nullable=True, comment='网卡IP地址'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='状态：0停用，1启用'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['ops_server.id'], name='fk_ops_server_network_server'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'interface_name', name='uk_ops_server_network_interface'),
    comment='服务器网卡资产表'
    )
    op.create_index('idx_ops_server_network_server_id', 'ops_server_network', ['server_id'], unique=False)
    op.create_table('ops_server_service',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='服务资产ID'),
    sa.Column('server_id', mysql.BIGINT(unsigned=True), nullable=False, comment='服务器ID'),
    sa.Column('service_name', sa.String(length=64), nullable=False, comment='systemd服务名称'),
    sa.Column('display_name', sa.String(length=128), nullable=True, comment='展示名称'),
    sa.Column('service_type', sa.String(length=32), server_default=sa.text("'SYSTEMD'"), nullable=False, comment='SYSTEMD/DOCKER/CUSTOM'),
    sa.Column('is_whitelisted', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='是否允许执行受控操作'),
    sa.Column('is_critical', mysql.TINYINT(), server_default=sa.text('0'), nullable=False, comment='是否为关键服务'),
    sa.Column('current_status', sa.String(length=32), nullable=True, comment='RUNNING/STOPPED/FAILED/UNKNOWN'),
    sa.Column('last_checked_at', mysql.DATETIME(fsp=3), nullable=True, comment='最后检查时间'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='状态：0停用，1启用'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['ops_server.id'], name='fk_ops_server_service_server'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'service_name', name='uk_ops_server_service'),
    comment='服务器服务资产表'
    )
    op.create_index('idx_ops_server_service_critical', 'ops_server_service', ['is_critical', 'current_status'], unique=False)
    op.create_index('idx_ops_server_service_status', 'ops_server_service', ['server_id', 'current_status'], unique=False)
    op.create_table('ops_task_target',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='任务目标ID'),
    sa.Column('task_id', mysql.BIGINT(unsigned=True), nullable=False, comment='任务ID'),
    sa.Column('server_id', mysql.BIGINT(unsigned=True), nullable=False, comment='目标服务器ID'),
    sa.Column('target_status', sa.String(length=24), server_default=sa.text("'PENDING'"), nullable=False, comment='PENDING/RUNNING/SUCCESS/FAILED/TIMEOUT/CANCELLED'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['ops_server.id'], name='fk_ops_task_target_server'),
    sa.ForeignKeyConstraint(['task_id'], ['ops_task.id'], name='fk_ops_task_target_task'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'server_id', name='uk_ops_task_target'),
    comment='任务目标服务器表'
    )
    op.create_index('idx_ops_task_target_server_id', 'ops_task_target', ['server_id'], unique=False)
    op.create_index('idx_ops_task_target_status', 'ops_task_target', ['target_status'], unique=False)
    op.create_table('sys_operation_log',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='操作日志ID'),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=True, comment='操作用户ID'),
    sa.Column('username', sa.String(length=64), nullable=True, comment='操作用户名快照'),
    sa.Column('module', sa.String(length=64), nullable=False, comment='操作模块'),
    sa.Column('operation', sa.String(length=64), nullable=False, comment='操作类型'),
    sa.Column('http_method', sa.String(length=16), nullable=True, comment='HTTP方法'),
    sa.Column('request_path', sa.String(length=255), nullable=True, comment='请求路径'),
    sa.Column('target_type', sa.String(length=32), nullable=True, comment='目标类型'),
    sa.Column('target_id', mysql.BIGINT(unsigned=True), nullable=True, comment='目标ID'),
    sa.Column('server_id', mysql.BIGINT(unsigned=True), nullable=True, comment='目标服务器ID'),
    sa.Column('request_ip', sa.String(length=64), nullable=True, comment='请求IP'),
    sa.Column('request_id', sa.String(length=64), nullable=True, comment='请求ID'),
    sa.Column('request_params', mysql.JSON(), nullable=True, comment='请求参数，禁止记录密码和Token'),
    sa.Column('result_status', sa.String(length=24), nullable=False, comment='SUCCESS/FAILED'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('duration_ms', mysql.BIGINT(unsigned=True), nullable=True, comment='请求耗时，单位：毫秒'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['ops_server.id'], name='fk_sys_operation_log_server'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], name='fk_sys_operation_log_user'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统操作审计日志表'
    )
    op.create_index('idx_sys_operation_log_created_at', 'sys_operation_log', ['created_at'], unique=False)
    op.create_index('idx_sys_operation_log_module_time', 'sys_operation_log', ['module', 'created_at'], unique=False)
    op.create_index('idx_sys_operation_log_server_time', 'sys_operation_log', ['server_id', 'created_at'], unique=False)
    op.create_index('idx_sys_operation_log_status_time', 'sys_operation_log', ['result_status', 'created_at'], unique=False)
    op.create_index('idx_sys_operation_log_user_time', 'sys_operation_log', ['user_id', 'created_at'], unique=False)
    op.create_table('alert_event_log',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='告警事件日志ID'),
    sa.Column('event_id', mysql.BIGINT(unsigned=True), nullable=False, comment='告警事件ID'),
    sa.Column('old_status', sa.String(length=24), nullable=True, comment='原状态'),
    sa.Column('new_status', sa.String(length=24), nullable=False, comment='新状态'),
    sa.Column('current_value', sa.Numeric(precision=12, scale=4), nullable=True, comment='事件值'),
    sa.Column('message', sa.String(length=500), nullable=True, comment='状态变化说明'),
    sa.Column('operator_id', mysql.BIGINT(unsigned=True), nullable=True, comment='操作人，系统操作可为空'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['alert_event.id'], name='fk_alert_event_log_event'),
    sa.ForeignKeyConstraint(['operator_id'], ['sys_user.id'], name='fk_alert_event_log_operator'),
    sa.PrimaryKeyConstraint('id'),
    comment='告警状态变化日志表'
    )
    op.create_index('fk_alert_event_log_operator', 'alert_event_log', ['operator_id'], unique=False)
    op.create_index('idx_alert_event_log_event_time', 'alert_event_log', ['event_id', 'created_at'], unique=False)
    op.create_table('monitor_container_metric',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='容器指标记录ID'),
    sa.Column('container_asset_id', mysql.BIGINT(unsigned=True), nullable=False, comment='容器资产ID'),
    sa.Column('server_id', mysql.BIGINT(unsigned=True), nullable=False, comment='服务器ID'),
    sa.Column('container_id', sa.String(length=128), nullable=False, comment='容器ID快照'),
    sa.Column('container_status', sa.String(length=32), nullable=True, comment='RUNNING/STOPPED/PAUSED/EXITED'),
    sa.Column('cpu_usage', sa.Numeric(precision=7, scale=3), nullable=True, comment='CPU使用率'),
    sa.Column('memory_usage', sa.Numeric(precision=7, scale=3), nullable=True, comment='内存使用率'),
    sa.Column('memory_used_bytes', mysql.BIGINT(unsigned=True), nullable=True, comment='容器已使用内存'),
    sa.Column('network_in_bytes', mysql.BIGINT(unsigned=True), nullable=True, comment='累计入站字节数'),
    sa.Column('network_out_bytes', mysql.BIGINT(unsigned=True), nullable=True, comment='累计出站字节数'),
    sa.Column('restart_count', mysql.INTEGER(unsigned=True), nullable=True, comment='重启次数'),
    sa.Column('collected_at', mysql.DATETIME(fsp=3), nullable=False, comment='采集时间'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['container_asset_id'], ['ops_server_container.id'], name='fk_monitor_container_metric_asset'),
    sa.ForeignKeyConstraint(['server_id'], ['ops_server.id'], name='fk_monitor_container_metric_server'),
    sa.PrimaryKeyConstraint('id'),
    comment='Docker容器监控指标表'
    )
    op.create_index('idx_monitor_container_metric_asset_time', 'monitor_container_metric', ['container_asset_id', 'collected_at'], unique=False)
    op.create_index('idx_monitor_container_metric_server_time', 'monitor_container_metric', ['server_id', 'collected_at'], unique=False)
    op.create_table('monitor_disk_metric',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='磁盘指标记录ID'),
    sa.Column('disk_id', mysql.BIGINT(unsigned=True), nullable=False, comment='磁盘资产ID'),
    sa.Column('server_id', mysql.BIGINT(unsigned=True), nullable=False, comment='服务器ID'),
    sa.Column('collected_at', mysql.DATETIME(fsp=3), nullable=False, comment='采集时间'),
    sa.Column('used_bytes', mysql.BIGINT(unsigned=True), nullable=True, comment='已使用容量，单位：字节'),
    sa.Column('total_bytes', mysql.BIGINT(unsigned=True), nullable=True, comment='总容量，单位：字节'),
    sa.Column('usage_percent', sa.Numeric(precision=5, scale=2), nullable=True, comment='使用率，百分比'),
    sa.Column('read_bytes', mysql.BIGINT(unsigned=True), nullable=True, comment='累计读取字节数'),
    sa.Column('write_bytes', mysql.BIGINT(unsigned=True), nullable=True, comment='累计写入字节数'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['disk_id'], ['ops_server_disk.id'], name='fk_monitor_disk_metric_disk'),
    sa.ForeignKeyConstraint(['server_id'], ['ops_server.id'], name='fk_monitor_disk_metric_server'),
    sa.PrimaryKeyConstraint('id'),
    comment='磁盘监控指标表'
    )
    op.create_index('idx_monitor_disk_metric_disk_time', 'monitor_disk_metric', ['disk_id', 'collected_at'], unique=False)
    op.create_index('idx_monitor_disk_metric_server_time', 'monitor_disk_metric', ['server_id', 'collected_at'], unique=False)
    op.create_table('monitor_network_metric',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='网卡指标记录ID'),
    sa.Column('network_id', mysql.BIGINT(unsigned=True), nullable=False, comment='网卡资产ID'),
    sa.Column('server_id', mysql.BIGINT(unsigned=True), nullable=False, comment='服务器ID'),
    sa.Column('collected_at', mysql.DATETIME(fsp=3), nullable=False, comment='采集时间'),
    sa.Column('bytes_received', mysql.BIGINT(unsigned=True), nullable=True, comment='累计接收字节数'),
    sa.Column('bytes_sent', mysql.BIGINT(unsigned=True), nullable=True, comment='累计发送字节数'),
    sa.Column('packets_received', mysql.BIGINT(unsigned=True), nullable=True, comment='累计接收数据包数'),
    sa.Column('packets_sent', mysql.BIGINT(unsigned=True), nullable=True, comment='累计发送数据包数'),
    sa.Column('errors_received', mysql.INTEGER(unsigned=True), nullable=True, comment='接收错误数'),
    sa.Column('errors_sent', mysql.INTEGER(unsigned=True), nullable=True, comment='发送错误数'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['ops_server_network.id'], name='fk_monitor_network_metric_network'),
    sa.ForeignKeyConstraint(['server_id'], ['ops_server.id'], name='fk_monitor_network_metric_server'),
    sa.PrimaryKeyConstraint('id'),
    comment='网卡监控指标表'
    )
    op.create_index('idx_monitor_network_metric_network_time', 'monitor_network_metric', ['network_id', 'collected_at'], unique=False)
    op.create_index('idx_monitor_network_metric_server_time', 'monitor_network_metric', ['server_id', 'collected_at'], unique=False)
    op.create_table('ops_task_execution',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='任务执行记录ID'),
    sa.Column('task_id', mysql.BIGINT(unsigned=True), nullable=False, comment='任务ID'),
    sa.Column('target_id', mysql.BIGINT(unsigned=True), nullable=False, comment='任务目标ID'),
    sa.Column('server_id', mysql.BIGINT(unsigned=True), nullable=False, comment='服务器ID'),
    sa.Column('status', sa.String(length=24), server_default=sa.text("'PENDING'"), nullable=False, comment='PENDING/RUNNING/SUCCESS/FAILED/TIMEOUT/CANCELLED'),
    sa.Column('exit_code', mysql.INTEGER(), nullable=True, comment='进程退出码'),
    sa.Column('result_text', mysql.MEDIUMTEXT(), nullable=True, comment='执行结果'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('started_at', mysql.DATETIME(fsp=3), nullable=True, comment='开始时间'),
    sa.Column('finished_at', mysql.DATETIME(fsp=3), nullable=True, comment='结束时间'),
    sa.Column('duration_ms', mysql.BIGINT(unsigned=True), nullable=True, comment='执行耗时，单位：毫秒'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['ops_server.id'], name='fk_ops_task_execution_server'),
    sa.ForeignKeyConstraint(['target_id'], ['ops_task_target.id'], name='fk_ops_task_execution_target'),
    sa.ForeignKeyConstraint(['task_id'], ['ops_task.id'], name='fk_ops_task_execution_task'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'target_id', name='uk_ops_task_execution_target'),
    comment='任务执行记录表'
    )
    op.create_index('fk_ops_task_execution_target', 'ops_task_execution', ['target_id'], unique=False)
    op.create_index('idx_ops_task_execution_server_time', 'ops_task_execution', ['server_id', 'created_at'], unique=False)
    op.create_index('idx_ops_task_execution_task_status', 'ops_task_execution', ['task_id', 'status'], unique=False)
    op.create_table('ops_task_log',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='任务日志ID'),
    sa.Column('execution_id', mysql.BIGINT(unsigned=True), nullable=False, comment='任务执行记录ID'),
    sa.Column('log_level', sa.String(length=16), server_default=sa.text("'INFO'"), nullable=False, comment='DEBUG/INFO/WARN/ERROR'),
    sa.Column('log_content', mysql.MEDIUMTEXT(), nullable=False, comment='日志内容'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['ops_task_execution.id'], name='fk_ops_task_log_execution'),
    sa.PrimaryKeyConstraint('id'),
    comment='任务执行日志表'
    )
    op.create_index('idx_ops_task_log_execution_time', 'ops_task_log', ['execution_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ops_task_log_execution_time', table_name='ops_task_log')
    op.drop_table('ops_task_log')
    op.drop_index('idx_ops_task_execution_task_status', table_name='ops_task_execution')
    op.drop_index('idx_ops_task_execution_server_time', table_name='ops_task_execution')
    op.drop_index('fk_ops_task_execution_target', table_name='ops_task_execution')
    op.drop_table('ops_task_execution')
    op.drop_index('idx_monitor_network_metric_server_time', table_name='monitor_network_metric')
    op.drop_index('idx_monitor_network_metric_network_time', table_name='monitor_network_metric')
    op.drop_table('monitor_network_metric')
    op.drop_index('idx_monitor_disk_metric_server_time', table_name='monitor_disk_metric')
    op.drop_index('idx_monitor_disk_metric_disk_time', table_name='monitor_disk_metric')
    op.drop_table('monitor_disk_metric')
    op.drop_index('idx_monitor_container_metric_server_time', table_name='monitor_container_metric')
    op.drop_index('idx_monitor_container_metric_asset_time', table_name='monitor_container_metric')
    op.drop_table('monitor_container_metric')
    op.drop_index('idx_alert_event_log_event_time', table_name='alert_event_log')
    op.drop_index('fk_alert_event_log_operator', table_name='alert_event_log')
    op.drop_table('alert_event_log')
    op.drop_index('idx_sys_operation_log_user_time', table_name='sys_operation_log')
    op.drop_index('idx_sys_operation_log_status_time', table_name='sys_operation_log')
    op.drop_index('idx_sys_operation_log_server_time', table_name='sys_operation_log')
    op.drop_index('idx_sys_operation_log_module_time', table_name='sys_operation_log')
    op.drop_index('idx_sys_operation_log_created_at', table_name='sys_operation_log')
    op.drop_table('sys_operation_log')
    op.drop_index('idx_ops_task_target_status', table_name='ops_task_target')
    op.drop_index('idx_ops_task_target_server_id', table_name='ops_task_target')
    op.drop_table('ops_task_target')
    op.drop_index('idx_ops_server_service_status', table_name='ops_server_service')
    op.drop_index('idx_ops_server_service_critical', table_name='ops_server_service')
    op.drop_table('ops_server_service')
    op.drop_index('idx_ops_server_network_server_id', table_name='ops_server_network')
    op.drop_table('ops_server_network')
    op.drop_index('idx_ops_server_disk_server_id', table_name='ops_server_disk')
    op.drop_table('ops_server_disk')
    op.drop_index('idx_ops_server_container_status', table_name='ops_server_container')
    op.drop_index('idx_ops_server_container_critical', table_name='ops_server_container')
    op.drop_table('ops_server_container')
    op.drop_index('idx_ops_agent_token_server_status', table_name='ops_agent_token')
    op.drop_table('ops_agent_token')
    op.drop_index('idx_ops_agent_heartbeat_server_time', table_name='ops_agent_heartbeat')
    op.drop_index('idx_ops_agent_heartbeat_received_at', table_name='ops_agent_heartbeat')
    op.drop_table('ops_agent_heartbeat')
    op.drop_index('idx_monitor_server_metric_server_time', table_name='monitor_server_metric')
    op.drop_index('idx_monitor_server_metric_collected_at', table_name='monitor_server_metric')
    op.drop_table('monitor_server_metric')
    op.drop_index('idx_monitor_process_snapshot_server_time', table_name='monitor_process_snapshot')
    op.drop_index('idx_monitor_process_snapshot_server_pid_time', table_name='monitor_process_snapshot')
    op.drop_table('monitor_process_snapshot')
    op.drop_index('idx_alert_event_status_time', table_name='alert_event')
    op.drop_index('idx_alert_event_server_status', table_name='alert_event')
    op.drop_index('idx_alert_event_rule_id', table_name='alert_event')
    op.drop_index('fk_alert_event_acknowledged_by', table_name='alert_event')
    op.drop_table('alert_event')
    op.drop_index('idx_sys_user_role_role_id', table_name='sys_user_role')
    op.drop_table('sys_user_role')
    op.drop_index('idx_sys_role_permission_permission_id', table_name='sys_role_permission')
    op.drop_table('sys_role_permission')
    op.drop_index('idx_sys_login_log_username_time', table_name='sys_login_log')
    op.drop_index('idx_sys_login_log_user_time', table_name='sys_login_log')
    op.drop_index('idx_sys_login_log_status_time', table_name='sys_login_log')
    op.drop_table('sys_login_log')
    op.drop_index('idx_ops_task_status', table_name='ops_task')
    op.drop_index('idx_ops_task_schedule', table_name='ops_task')
    op.drop_index('idx_ops_task_creator_time', table_name='ops_task')
    op.drop_index('fk_ops_task_confirmed_by', table_name='ops_task')
    op.drop_table('ops_task')
    op.drop_index('idx_ops_server_status', table_name='ops_server')
    op.drop_index('idx_ops_server_last_heartbeat', table_name='ops_server')
    op.drop_index('idx_ops_server_hostname', table_name='ops_server')
    op.drop_index('idx_ops_server_agent_status', table_name='ops_server')
    op.drop_index('fk_ops_server_created_by', table_name='ops_server')
    op.drop_table('ops_server')
    op.drop_index('idx_alert_rule_target_enabled', table_name='alert_rule')
    op.drop_index('idx_alert_rule_metric_enabled', table_name='alert_rule')
    op.drop_index('fk_alert_rule_created_by', table_name='alert_rule')
    op.drop_table('alert_rule')
    op.drop_index('idx_sys_user_status', table_name='sys_user')
    op.drop_index('idx_sys_user_deleted_at', table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_index('idx_sys_role_status', table_name='sys_role')
    op.drop_table('sys_role')
    op.drop_index('idx_sys_permission_type_status', table_name='sys_permission')
    op.drop_index('idx_sys_permission_parent_id', table_name='sys_permission')
    op.drop_table('sys_permission')
    # ### end Alembic commands ###
