"""metric daily archive

Revision ID: 4f50bb136572
Revises: 7aa13a973276
Create Date: 2026-10-03 22:07:29.709328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4f50bb136572'
down_revision: Union[str, None] = '7aa13a973276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitor_server_metric_daily',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='聚合记录ID'),
    sa.Column('server_id', mysql.BIGINT(unsigned=True), nullable=False, comment='服务器ID'),
    sa.Column('metric_date', sa.Date(), nullable=False, comment='统计日期'),
    sa.Column('cpu_usage_avg', sa.Numeric(precision=12, scale=4), nullable=True, comment='CPU 使用率均值'),
    sa.Column('cpu_usage_max', sa.Numeric(precision=12, scale=4), nullable=True, comment='CPU 使用率峰值'),
    sa.Column('memory_usage_avg', sa.Numeric(precision=12, scale=4), nullable=True, comment='内存使用率均值'),
    sa.Column('memory_usage_max', sa.Numeric(precision=12, scale=4), nullable=True, comment='内存使用率峰值'),
    sa.Column('disk_usage_avg', sa.Numeric(precision=12, scale=4), nullable=True, comment='磁盘使用率均值'),
    sa.Column('disk_usage_max', sa.Numeric(precision=12, scale=4), nullable=True, comment='磁盘使用率峰值'),
    sa.Column('load_1m_avg', sa.Numeric(precision=12, scale=4), nullable=True, comment='1分钟Load均值'),
    sa.Column('load_1m_max', sa.Numeric(precision=12, scale=4), nullable=True, comment='1分钟Load峰值'),
    sa.Column('tcp_connections_avg', sa.Numeric(precision=12, scale=4), nullable=True, comment='TCP连接数均值'),
    sa.Column('tcp_connections_max', sa.Numeric(precision=12, scale=4), nullable=True, comment='TCP连接数峰值'),
    sa.Column('sample_count', mysql.INTEGER(unsigned=True), nullable=False, comment='参与聚合的原始样本数'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['server_id'], ['ops_server.id'], name='fk_metric_daily_server'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'metric_date', name='uk_metric_daily_server_date'),
    comment='服务器指标日聚合（长期归档）'
    )
    op.create_index('idx_metric_daily_date', 'monitor_server_metric_daily', ['metric_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_metric_daily_date', table_name='monitor_server_metric_daily')
    op.drop_table('monitor_server_metric_daily')
    # ### end Alembic commands ###
