"""agent request signing

Revision ID: 7aa13a973276
Revises: b1805a5af57f
Create Date: 2026-10-03 20:04:51.586594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7aa13a973276'
down_revision: Union[str, None] = 'b1805a5af57f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ops_agent_token', sa.Column('signing_public_key', sa.String(length=128), nullable=True, comment='Ed25519 公钥（base64），用于请求签名'))
    op.add_column('ops_agent_token', sa.Column('signing_algorithm', sa.String(length=16), server_default=sa.text("'ed25519'"), nullable=True, comment='签名算法'))
    op.add_column('ops_agent_token', sa.Column('key_registered_at', mysql.DATETIME(fsp=3), nullable=True, comment='公钥注册时间'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ops_agent_token', 'key_registered_at')
    op.drop_column('ops_agent_token', 'signing_algorithm')
    op.drop_column('ops_agent_token', 'signing_public_key')
    # ### end Alembic commands ###
