"""task retry and idempotency

Revision ID: b1805a5af57f
Revises: 096f952de48e
Create Date: 2026-10-03 18:19:46.312830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b1805a5af57f'
down_revision: Union[str, None] = '096f952de48e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ops_task', sa.Column('max_attempts', mysql.INTEGER(unsigned=True), server_default=sa.text('3'), nullable=False, comment='最大尝试次数'))
    op.add_column('ops_task', sa.Column('attempt', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=False, comment='当前/最近尝试编号'))
    op.add_column('ops_task', sa.Column('deadline_at', mysql.DATETIME(fsp=3), nullable=True, comment='任务整体截止时间'))
    op.add_column('ops_task', sa.Column('idempotency_key', sa.String(length=128), nullable=True, comment='幂等键，防止重复创建'))
    op.create_unique_constraint('uk_ops_task_idempotency', 'ops_task', ['idempotency_key'])
    op.add_column('ops_task_execution', sa.Column('attempt', mysql.INTEGER(unsigned=True), server_default=sa.text('1'), nullable=False, comment='尝试编号'))
    op.add_column('ops_task_execution', sa.Column('next_retry_at', mysql.DATETIME(fsp=3), nullable=True, comment='下次重试时间'))
    op.add_column('ops_task_execution', sa.Column('error_type', sa.String(length=32), nullable=True, comment='标准化错误类型'))
    op.alter_column('ops_task_execution', 'status',
               existing_type=mysql.VARCHAR(length=24),
               comment='PENDING/RUNNING/SUCCESS/FAILED/TIMEOUT/CANCELLED/RETRYING/DEAD',
               existing_comment='PENDING/RUNNING/SUCCESS/FAILED/TIMEOUT/CANCELLED',
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'"))
    op.drop_constraint('uk_ops_task_execution_target', 'ops_task_execution', type_='unique')
    op.create_unique_constraint('uk_ops_task_execution_target', 'ops_task_execution', ['task_id', 'target_id', 'attempt'])
    op.create_index('idx_ops_task_execution_retry', 'ops_task_execution', ['status', 'next_retry_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ops_task_execution_retry', table_name='ops_task_execution')
    op.drop_constraint('uk_ops_task_execution_target', 'ops_task_execution', type_='unique')
    op.create_unique_constraint('uk_ops_task_execution_target', 'ops_task_execution', ['task_id', 'target_id'])
    op.alter_column('ops_task_execution', 'status',
               existing_type=mysql.VARCHAR(length=24),
               comment='PENDING/RUNNING/SUCCESS/FAILED/TIMEOUT/CANCELLED',
               existing_comment='PENDING/RUNNING/SUCCESS/FAILED/TIMEOUT/CANCELLED/RETRYING/DEAD',
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'"))
    op.drop_column('ops_task_execution', 'error_type')
    op.drop_column('ops_task_execution', 'next_retry_at')
    op.drop_column('ops_task_execution', 'attempt')
    op.drop_constraint('uk_ops_task_idempotency', 'ops_task', type_='unique')
    op.drop_column('ops_task', 'idempotency_key')
    op.drop_column('ops_task', 'deadline_at')
    op.drop_column('ops_task', 'attempt')
    op.drop_column('ops_task', 'max_attempts')
    # ### end Alembic commands ###
